### ISSUE TITLE
demo app implementation is outdated

### ISSUE THREAD

**Issue by elvinristi** [microsoftgraph/universalprint-samples#8]
Hello.

This app implementation is outdated.

fails already on getting oauth token due missing client_secret and other params.

Also calls like createJob are having different request body.

Could this sample app be updated to workable sample?

From https://docs.microsoft.com/en-us/graph/changelog
- Deprecated **uploadData** action on _printDocument_ resource.
- Added the **createUploadSession** action for _printDocument_.
- **startPrintJob** action on _printJob_ resource has been renamed to start
- etc.

Thanks!

**Comment by braedenp-msft** [comment]
The old sample app has been replaced with new ones.
