### ISSUE TITLE
Universal Print Graph API (print/shares) returns status code 403

### ISSUE THREAD

**Issue by Gucchiy** [microsoftgraph/universalprint-samples#9]
I’m testing this UP Graph API sample.
But using /print/shares API, that returns status of 403.

```
/** Invokes List Print Shares Microsoft Graph API and returns list of user PrinterShares.
 * @returns List of printershares objects.
 */
export const getPrinterShares = async (authToken: string): Promise<IPrinterShare[]> => {
    const listPrintsRequestInit = {
        method: 'GET',
        mode: 'cors' as RequestMode,
        headers: {
            'Accept': 'application/json',
            'Authorization': 'Bearer ' + authToken
        },
    };

    const url = `${hostUrl}/print/shares?$select=id,name,defaults,capabilities`;

    const response = await fetch(url, listPrintsRequestInit) as Response;
    const value = await response.json() as IGraphPrinterSharesResponse;
    const printShares = value.value as IPrinterShare[];
    return printShares;
}
```

Failed to load resource: the server responded with a status of 403 (Forbidden) [https://graph.microsoft.com/beta/print/shares?$select=id,name,defaults,capabilities]

Does anyone have any information for this issue? This code was working well about a month ago.
I can get shared printer list by using PowerShell UP commands.

**Comment by braedenp-msft** [comment]
Are you able to send the request ID via private message? We can look into this failure for you.

**Comment by braedenp-msft** [comment]
The old sample app has been replaced with new ones.
